# Dockerfile del contenedor base
FROM docker:latest

RUN apk add --no-cache git bash

WORKDIR /app

# Clonar el repositorio con los códigos
RUN git clone https://github.com/Siberodi/docker_2.git /app

# Dar permisos de ejecución al script
RUN chmod +x /app/run_benchmark.sh

CMD ["bash", "/app/run_benchmark.sh"]
